{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pv-safe.serviceAccountName" . }}
  namespace: {{ include "pv-safe.namespace" . }}
  labels:
    {{- include "pv-safe.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
