apiVersion: v1
kind: Service
metadata:
  name: {{ include "pv-safe.fullname" . }}-webhook
  namespace: {{ include "pv-safe.namespace" . }}
  labels:
    {{- include "pv-safe.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "pv-safe.selectorLabels" . | nindent 4 }}
  ports:
    - name: https
      port: 443
      targetPort: {{ .Values.webhook.port }}
      protocol: TCP
